version: '3.8'
networks:
  test_app_net:
services:
  app_1:
    container_name: app_1
    environment:
      - PORT=3001
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - test_app_net
  app_2:
    container_name: app_2
    environment:
      - PORT=3001
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - test_app_net
  app_load_balance:
    container_name: app_load_balance
    image: nginx:1.13.0-alpine
    volumes:
      - ./my_nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '3002:8888'
    networks:
      - test_app_net
